### PR TITLE
Retry requests when rate limited

### PR DESCRIPTION
**Pull request by anekkanti**
## What was changed
The api client will retry when it runs into rate limiting.

## Why?
This capability was accidentally removed in [PR-121](https://github.com/temporalio/terraform-provider-temporalcloud/pull/121)
This change adds the middleware back on the client.

## Checklist

1. Closes 
https://github.com/temporalio/terraform-provider-temporalcloud/issues/142

2. How was this tested:
- [x] CI
- [ ] Manual

### CODE REVIEW

**Comment by jlacefie** [comment]
TY Abhinav. Reviewing this, it appears I removed a bit too much when replacing the previous manual dial with the Go client and we lost the backoff retry options, yes? 

I'll pull down and test now and validate this resolves the issue. For context, I ran into this earlier this week and believe it can be recreated easily.

**Comment by anekkanti** [comment]
> TY Abhinav. Reviewing this, it appears I removed a bit too much when replacing the previous manual dial with the Go client and we lost the backoff retry options, yes?

Yes that is my understanding. I don't think the SDK we use provides this out of the box. 

> I'll pull down and test now and validate this resolves the issue. For context, I ran into this earlier this week and believe it can be recreated easily.

Thank you, I am also planning to do some tests on my end. More for my experience.

**Comment by jlacefie** [comment]
Thanks.  Did you happen to ask if the Go SDK provides backoff support, similar to what's supported for WFs and Activities?

**Review by jlacefie — APPROVED** [review]
TY. Looks good. This resolved the pervious errors experienced locally.  

As a future item, we may want to explore if the SDK already supports retry policies for the Cloud Ops API and/or make a request to that repo and then refactor to use the SDK.

**Pull request merged**
